# Generated by Django 5.1.3 on 2024-12-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Exercise', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.IntegerField(help_text='Duration of the activity in minutes')),
                ('heart_rate', models.IntegerField(help_text='Average heart rate during the exercise')),
                ('calories_burned', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
