# Generated by Django 5.1.4 on 2024-12-16 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Exercise', max_length=255)),
                ('duration_minutes', models.IntegerField(help_text='Duration of the activity in minutes', validators=[django.core.validators.MinValueValidator(1, message='N/A, please try again'), django.core.validators.MaxValueValidator(300, message='Please limit exercise to 5 hours per session')])),
                ('heart_rate', models.IntegerField(help_text='Average heart rate during the exercise', validators=[django.core.validators.MinValueValidator(40, message='N/A, please try again'), django.core.validators.MaxValueValidator(220, message='N/A, please try again')])),
                ('calories_burned', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
