# Generated by Django 5.1.4 on 2024-12-16 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_add_user_to_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activity',
            new_name='tracker_act_date_208f4a_idx',
            old_name='tracker_act_date_2c4af3_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='tracker_act_calorie_e9788a_idx',
            old_name='tracker_act_calorie_1a9d23_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='tracker_act_user_id_062daa_idx',
            old_name='tracker_act_user_id_8f1234_idx',
        ),
        migrations.AlterField(
            model_name='activity',
            name='calories_burned',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(db_index=True, default='Exercise', max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
